services:
  marketPlace:
    build:
      context: .
    image: marketplace-app
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=chave-super-secreta-para-jwt-1234567890


  #    depends_on:
#      - mysql
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/marketplace_db
#      - SPRING_DATASOURCE_USERNAME=usuario
#      - SPRING_DATASOURCE_PASSWORD=senha

  security:
    build:
      context: ../security
    image: security-app
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=chave-super-secreta-para-jwt-1234567890




#    depends_on:
#      - mysql
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/security_db
#      - SPRING_DATASOURCE_USERNAME=usuario
#      - SPRING_DATASOURCE_PASSWORD=senha

#  mysql:
#    image: mysql:8.0
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpass
#      MYSQL_DATABASE: marketplace_db
#      MYSQL_USER: usuario
#      MYSQL_PASSWORD: senha
#    volumes:
#      - mysql-data:/var/lib/mysql
#
#volumes:
#  mysql-data: